# The files needed for distribution
filegroup(
    name = "distribution",
    srcs = glob(
        ["*"],
        allow_empty = True,
    ),
    visibility = [
        "//:__pkg__",
        "//distribution:__pkg__",
    ],
)
