# Not really c++, but stops travis from listing a language.
language: c++

matrix:
  include:
    # -----------------------------------------------------------------
    # Linux hosted tests

    - os: linux
      dist: trusty
      sudo: false
      env: BAZEL=HEAD
    - os: linux
      dist: trusty
      sudo: false
      env: BUILDIFER=RELEASE

    # -----------------------------------------------------------------
    # macOS hosted tests

    - os: osx
      osx_image: xcode9.3
      env: BAZEL=HEAD
    # No need for a BUILDIFER run on mac, the results will be the same.
    # And linux boxes test faster on travis, so just use the one.

before_install:
  - ./.travis_install.sh

script:
  - ./.travis_build.sh

notifications:
  email: false
